
import React from 'react';
import { Roadmap, Resource } from './types';

// Icons (Heroicons)
// Functional components with JSX, to be transpiled by Babel.
const CodeBracketIcon = (props: React.SVGProps<SVGSVGElement>): React.JSX.Element => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" {...props}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M17.25 6.75 22.5 12l-5.25 5.25m-10.5 0L1.5 12l5.25-5.25m7.5-3-4.5 16.5" />
  </svg>
);

const ServerStackIcon = (props: React.SVGProps<SVGSVGElement>): React.JSX.Element => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" {...props}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M6.75 7.5l3 2.25-3 2.25m4.5 0h3m-9 8.25h13.5A2.25 2.25 0 0 0 21 18V6a2.25 2.25 0 0 0-2.25-2.25H5.25A2.25 2.25 0 0 0 3 6v12a2.25 2.25 0 0 0 2.25 2.25Z" />
  </svg>
);

const ChartBarIcon = (props: React.SVGProps<SVGSVGElement>): React.JSX.Element => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" {...props}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 0 1 3 19.875v-6.75ZM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V8.625ZM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V4.125Z" />
  </svg>
);


export const ROADMAPS_DATA: Roadmap[] = [
  {
    id: 'frontend',
    title: 'Frontend',
    concept: "Conviértete en un arquitecto de la experiencia digital. Aprenderás a construir la parte visible e interactiva de los sitios y aplicaciones web con la que los usuarios interactúan directamente. Dominarás tecnologías como HTML, CSS, JavaScript y frameworks modernos para crear interfaces atractivas, funcionales y responsivas.",
    focus: "Experiencia de Usuario (UX), Interfaz de Usuario (UI), diseño visual, interactividad.",
    icon: <CodeBracketIcon className="w-12 h-12 text-rei-blue dark:text-rei-green" />,
    imageUrl: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8ZnJvbnRlbmQlMjBkZXZlbG9wbWVudHxlbnwwfHwwfHx8MA&auto=format&fit=crop&w=600&q=80',
    modules: [
      { id: 'fundamentos_frontend', title: 'Fundamentos Esenciales', items: [
        { id: 'html', name: 'HTML5', description: 'Estructura semántica de la web.', technicalQuestions: ["¿Qué es DOCTYPE y para qué sirve?", "¿Cuál es la diferencia entre `<div>` y `<span>`?", "¿Qué son los atributos semánticos en HTML5? Da ejemplos.", "¿Para qué se utiliza el atributo 'alt' en las imágenes?", "Explica la diferencia entre `<article>` y `<section>`."] },
        { id: 'css', name: 'CSS3', description: 'Estilización y diseño visual, incluyendo Flexbox y Grid.', technicalQuestions: ["Explica el Box Model en CSS.", "¿Cuál es la diferencia entre `position: relative`, `absolute`, `fixed` y `sticky`?", "Describe la especificidad en CSS y cómo se calcula.", "¿Qué son los pseudo-elementos y las pseudo-clases en CSS? Da un ejemplo de cada uno.", "Explica cómo funciona Flexbox y menciona 3 propiedades importantes."] },
        { id: 'javascript', name: 'JavaScript (ES6+)', description: 'Lenguaje de programación fundamental para la web.', technicalQuestions: ["¿Qué es el 'hoisting' en JavaScript?", "Explica la diferencia entre `==` y `===`.", "¿Qué son las 'closures' y para qué se utilizan?", "Describe `map`, `filter` y `reduce` en arrays.", "Explica la diferencia entre `let`, `const` y `var`."] },
        { id: 'dom', name: 'Manipulación del DOM', description: 'Interactuar con la estructura de la página.', technicalQuestions: ["¿Qué es el DOM y cómo representa un documento HTML?", "Describe tres métodos comunes para seleccionar elementos del DOM.", "Explica la diferencia entre `innerHTML`, `innerText` y `textContent` al modificar nodos del DOM.", "¿Cómo agregarías un event listener a un elemento?", "Explica el concepto de 'event bubbling' y 'event capturing'."] },
        { id: 'responsive', name: 'Responsive Design', description: 'Adaptación a diferentes tamaños de pantalla.', technicalQuestions: ["¿Qué son las Media Queries y cómo se utilizan?", "Explica el concepto de 'Mobile First' en el diseño responsivo.", "Nombra tres unidades de medida relativas en CSS útiles para responsive design (ej: %, vw/vh, rem).", "¿Qué es una viewport y cómo se configura en HTML?"] },
      ]},
      { id: 'frameworks_frontend', title: 'Frameworks y Librerías', items: [
        { id: 'react', name: 'React.js', description: 'Librería popular para construir interfaces de usuario.', technicalQuestions: ["¿Qué es el Virtual DOM y cómo funciona en React?", "Explica el ciclo de vida de un componente en React (clases y hooks).", "¿Qué son los Hooks en React? Da ejemplos de `useState` y `useEffect`.", "Diferencia entre componentes controlados y no controlados en formularios React.", "¿Qué es JSX y cómo se transpila?"] },
        { id: 'vue', name: 'Vue.js', description: 'Framework progresivo para UI.', technicalQuestions: ["¿Qué es la instancia de Vue y cuál es su propósito?", "Explica las directivas en Vue.js (ej: v-if, v-for, v-bind, v-model).", "¿Cómo funciona el sistema de reactividad en Vue?", "Explica la diferencia entre `computed properties` y `methods` en Vue."] },
        { id: 'angular', name: 'Angular', description: 'Plataforma completa para desarrollo de aplicaciones.', technicalQuestions: ["¿Cuáles son los bloques de construcción principales de una aplicación Angular (Módulos, Componentes, Servicios, Directivas, Pipes)?", "Explica la diferencia entre `constructor` y `ngOnInit` en un componente Angular.", "¿Qué es la inyección de dependencias en Angular y cómo funciona?", "Describe los diferentes tipos de data binding en Angular (interpolación, property binding, event binding, two-way binding)."] },
        { id: 'state_management', name: 'Gestión de Estado (Redux, Zustand, Pinia)', description: 'Manejo de estado complejo en aplicaciones.', technicalQuestions: ["¿Por qué es necesaria la gestión de estado en aplicaciones grandes?", "Describe los principios básicos de Redux (Actions, Reducers, Store, Dispatch).", "¿Qué ventajas ofrecen librerías como Zustand o Pinia sobre Redux o Context API puro en React/Vue?", "Explica el concepto de 'inmutabilidad' en el contexto de la gestión de estado."] },
      ]},
      { id: 'herramientas_frontend', title: 'Herramientas y Ecosistema', items: [
        { id: 'git', name: 'Git y GitHub/GitLab', description: 'Control de versiones.', technicalQuestions: ["¿Cuál es la diferencia entre `git fetch` y `git pull`?", "Explica el propósito de `git rebase` y cuándo lo usarías en lugar de `git merge`.", "Describe un flujo de trabajo básico con ramas en Git (feature branches, hotfixes).", "¿Qué es un 'commit' y qué información debería contener un buen mensaje de commit?"] },
        { id: 'npm_yarn', name: 'NPM / Yarn', description: 'Gestores de paquetes.', technicalQuestions: ["¿Qué es `package.json` y qué información esencial contiene?", "¿Cuál es la diferencia entre `dependencies` y `devDependencies`?", "Explica el propósito de `package-lock.json` o `yarn.lock`.", "Describe el comando `npm install` y `npm update`."] },
        { id: 'bundlers', name: 'Webpack / Vite / Parcel', description: 'Empaquetadores de módulos.', technicalQuestions: ["¿Por qué son necesarios los empaquetadores de módulos en el desarrollo frontend moderno?", "Menciona dos tareas comunes que realiza un bundler (ej: transpilación, minificación, optimización de imágenes).", "Explica brevemente qué es el 'tree shaking'.", "¿En qué se diferencia Vite de Webpack en términos de servidor de desarrollo?"] },
        { id: 'testing_frontend', name: 'Testing (Jest, React Testing Library)', description: 'Pruebas unitarias y de integración.', technicalQuestions: ["¿Cuál es la diferencia entre pruebas unitarias, de integración y E2E?", "Describe el principio de 'Arrange-Act-Assert' (AAA) en testing.", "¿Qué tipo de cosas probarías en un componente React con React Testing Library?", "Explica qué es un 'mock' y cuándo lo usarías en tus pruebas."] },
        { id: 'apis_frontend', name: 'Consumo de APIs REST/GraphQL', description: 'Obtención de datos del backend.', technicalQuestions: ["¿Cómo realizarías una solicitud GET a una API REST usando `fetch` en JavaScript? Incluye manejo de errores.", "Menciona los métodos HTTP más comunes (GET, POST, PUT, DELETE) y su propósito.", "Explica brevemente qué es GraphQL y en qué se diferencia de REST en términos de obtención de datos.", "Describe el concepto de CORS y por qué es importante."] },
      ]},
    ],
  },
  {
    id: 'backend',
    title: 'Backend',
    concept: "Sé el motor detrás de las aplicaciones. Te enfocarás en la lógica del servidor, las bases de datos y las APIs (Interfaces de Programación de Aplicaciones) que hacen que todo funcione correctamente. Aprenderás a gestionar datos, asegurar la información y garantizar el rendimiento y la escalabilidad de las plataformas digitales.",
    focus: "Lógica de negocio, bases de datos, APIs, seguridad del servidor, rendimiento.",
    icon: <ServerStackIcon className="w-12 h-12 text-rei-blue dark:text-rei-green" />,
    imageUrl: 'https://images.unsplash.com/photo-1510511459019-5dda7724fd87?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmFja2VuZHxlbnwwfHwwfHx8MA&auto=format&fit=crop&w=600&q=80',
    modules: [
      { id: 'lenguajes_backend', title: 'Lenguajes de Programación', items: [
        { id: 'nodejs', name: 'Node.js (JavaScript/TypeScript)', description: 'Entorno de ejecución para JavaScript en servidor.', technicalQuestions: ["¿Qué es el Event Loop en Node.js y cómo funciona?", "Diferencia entre `require` e `import` en Node.js.", "Explica el manejo de errores en operaciones asíncronas en Node.js (callbacks, Promises, async/await).", "Explica qué es un 'stream' en Node.js y para qué se utiliza.", "¿Qué es Express.js y para qué se usa comúnmente en Node.js?"] },
        { id: 'python_backend', name: 'Python (Django, Flask)', description: 'Versátil y popular para desarrollo web.', technicalQuestions: ["Describe la diferencia entre una lista y una tupla en Python.", "¿Qué es el ORM en Django y qué ventajas ofrece?", "Explica el concepto de 'middleware' en Django o Flask.", "¿Qué son los decoradores en Python y cómo se usan?", "Diferencia entre Django y Flask."] },
        { id: 'java_backend', name: 'Java (Spring Boot)', description: 'Robusto y escalable para aplicaciones empresariales.', technicalQuestions: ["¿Qué es el Spring Framework y cuáles son sus principales módulos (Core, MVC, Data, Security)?", "Explica el concepto de Inyección de Dependencias (DI) en Spring y sus tipos.", "¿Qué es Spring Boot y qué problemas resuelve (autoconfiguración, starters)?", "Describe el patrón REST Controller en Spring MVC."] },
        { id: 'ruby_backend', name: 'Ruby (Ruby on Rails)', description: 'Conocido por su productividad.', technicalQuestions: ["¿Qué significa 'Convención sobre Configuración' en Ruby on Rails?", "Explica el patrón MVC (Modelo-Vista-Controlador) en el contexto de Rails.", "¿Qué son los 'gems' en Ruby y cómo se gestionan?", "Describe ActiveRecord en Rails y su propósito."] },
      ]},
      { id: 'bases_de_datos_backend', title: 'Bases de Datos', items: [
        { id: 'sql', name: 'Bases de Datos SQL (PostgreSQL, MySQL)', description: 'Modelos relacionales.', technicalQuestions: ["¿Qué es una clave primaria y una clave foránea? ¿Cuál es su importancia?", "Explica los diferentes tipos de JOINs en SQL (INNER, LEFT, RIGHT, FULL) con ejemplos.", "¿Qué es la normalización de bases de datos y por qué es importante? Describe las primeras tres formas normales (1NF, 2NF, 3NF).", "Explica qué son los índices en una base de datos y cómo mejoran el rendimiento."] },
        { id: 'nosql', name: 'Bases de Datos NoSQL (MongoDB, Redis)', description: 'Modelos no relacionales, flexibles.', technicalQuestions: ["Menciona dos diferencias principales entre bases de datos SQL y NoSQL.", "Describe un caso de uso donde una base de datos NoSQL como MongoDB sería preferible a una SQL.", "¿Para qué se utiliza comúnmente Redis? (cache, colas de mensajes, etc.)", "Explica el teorema CAP y cómo se relaciona con las bases de datos NoSQL."] },
        { id: 'orms', name: 'ORMs/ODMs (Sequelize, Mongoose)', description: 'Mapeo objeto-relacional/documento.', technicalQuestions: ["¿Qué es un ORM (Object-Relational Mapper) y qué ventajas proporciona?", "Explica el problema N+1 y cómo un ORM podría ayudar a mitigarlo (o causarlo).", "¿Cómo se definen las relaciones (uno a muchos, muchos a muchos) usando un ORM como Sequelize (Node.js) o Mongoose (Node.js/MongoDB)?", "Explica el concepto de migraciones de base de datos y cómo los ORMs las facilitan."] },
      ]},
      { id: 'apis_backend', title: 'APIs y Comunicación', items: [
        { id: 'rest_api', name: 'Diseño de APIs RESTful', description: 'Principios y buenas prácticas.', technicalQuestions: ["¿Cuáles son los principios clave de una API RESTful (stateless, cacheable, client-server, etc.)?", "Explica la idempotencia en el contexto de los métodos HTTP (GET, PUT, DELETE).", "¿Cómo versionarías una API REST? Menciona al menos dos estrategias.", "Describe los códigos de estado HTTP más comunes y su significado (200, 201, 400, 401, 403, 404, 500)."] },
        { id: 'graphql_api', name: 'GraphQL', description: 'Lenguaje de consulta para APIs.', technicalQuestions: ["¿Qué problema resuelve GraphQL que REST no aborda tan eficientemente (over-fetching, under-fetching)?", "Explica los conceptos de Query, Mutation y Subscription en GraphQL.", "¿Qué es un Schema en GraphQL y cuál es su rol?", "Diferencia entre Resolvers y Types en GraphQL."] },
        { id: 'autenticacion_autorizacion', name: 'Autenticación y Autorización (JWT, OAuth)', description: 'Seguridad de APIs.', technicalQuestions: ["¿Cuál es la diferencia entre autenticación y autorización?", "Explica cómo funciona la autenticación basada en JWT (JSON Web Tokens): estructura, firma, almacenamiento.", "¿Qué es OAuth 2.0 y para qué se utiliza? Describe los roles principales (Resource Owner, Client, Authorization Server, Resource Server).", "Menciona tres buenas prácticas para asegurar APIs."] },
      ]},
      { id: 'devops_backend', title: 'DevOps y Despliegue', items: [
        { id: 'docker', name: 'Docker', description: 'Contenerización de aplicaciones.', technicalQuestions: ["¿Qué es un contenedor Docker y en qué se diferencia de una máquina virtual?", "Explica el propósito de un `Dockerfile` y menciona 3 instrucciones comunes.", "¿Qué es Docker Compose y para qué se usa? Da un ejemplo de caso de uso.", "¿Qué son las imágenes de Docker y los registros de Docker (Docker Hub)?"] },
        { id: 'kubernetes', name: 'Kubernetes', description: 'Orquestación de contenedores.', technicalQuestions: ["¿Qué problemas resuelve Kubernetes que Docker Compose no puede (o no tan bien)?", "Describe los componentes principales de Kubernetes (Pod, Service, Deployment, Namespace).", "¿Qué es un Ingress en Kubernetes y para qué sirve?", "Explica el concepto de 'self-healing' en Kubernetes."] },
        { id: 'ci_cd', name: 'CI/CD (GitHub Actions, Jenkins)', description: 'Integración y despliegue continuo.', technicalQuestions: ["¿Qué significan CI (Integración Continua) y CD (Despliegue Continuo/Entrega Continua)? ¿Cuál es la diferencia entre Despliegue Continuo y Entrega Continua?", "Describe los beneficios de implementar un pipeline de CI/CD.", "Menciona los stages típicos de un pipeline de CI/CD.", "Compara brevemente GitHub Actions con Jenkins."] },
        { id: 'cloud_platforms', name: 'Plataformas Cloud (AWS, Azure, GCP)', description: 'Servicios en la nube.', technicalQuestions: ["Menciona tres tipos comunes de servicios ofrecidos por las plataformas cloud (IaaS, PaaS, SaaS) y da un ejemplo de cada uno.", "¿Qué es la escalabilidad elástica en la nube y cómo se diferencia de la escalabilidad vertical y horizontal?", "Nombra un servicio de cómputo (ej: EC2, Azure VM, Compute Engine) y un servicio de base de datos gestionada (ej: RDS, Azure SQL DB, Cloud SQL) de AWS, Azure o GCP.", "Explica el concepto de 'serverless' y menciona un servicio serverless (ej: AWS Lambda, Azure Functions, Google Cloud Functions)."] },
      ]},
    ],
  },
  {
    id: 'data-analysis',
    title: 'Análisis de Datos',
    concept: "Transforma datos crudos en decisiones inteligentes. Te sumergirás en el mundo de la extracción, procesamiento, análisis e interpretación de grandes volúmenes de información para descubrir tendencias, generar insights y comunicar tus hallazgos de forma efectiva mediante visualizaciones. Aprenderás a usar herramientas y lenguajes especializados para resolver problemas complejos.",
    focus: "Estadística, minería de datos, inteligencia de negocios, visualización, machine learning (básico).",
    icon: <ChartBarIcon className="w-12 h-12 text-rei-blue dark:text-rei-green" />,
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZGF0YSUyMGFuYWx5c2lzfGVufDB8fDB8fHww&auto=format&fit=crop&w=600&q=80',
    modules: [
      { id: 'fundamentos_datos', title: 'Fundamentos y Lenguajes', items: [
        { id: 'python_datos', name: 'Python (Pandas, NumPy, SciPy)', description: 'Librerías esenciales para análisis de datos.', technicalQuestions: ["Diferencia entre una Serie y un DataFrame en Pandas.", "¿Qué es un array de NumPy y en qué se diferencia de una lista de Python en términos de rendimiento y funcionalidad?", "Explica el uso de `groupby()` en Pandas para agregar datos. Da un ejemplo.", "¿Cómo manejarías valores faltantes (NaN) en un DataFrame de Pandas? Menciona al menos dos estrategias.", "Describe la función de SciPy en el ecosistema de análisis de datos de Python."] },
        { id: 'r_lang', name: 'R', description: 'Lenguaje estadístico y de visualización.', technicalQuestions: ["¿Cuáles son las estructuras de datos básicas en R (vector, list, data frame, matrix, array)? Describe brevemente cada una.", "Explica la diferencia entre `apply`, `lapply` y `sapply` en R. ¿Cuándo usarías cada una?", "¿Para qué se utiliza el paquete `ggplot2` en R? Menciona alguna característica distintiva.", "¿Qué es el 'tidyverse' en R?"] },
        { id: 'sql_datos', name: 'SQL para Análisis', description: 'Consultas y manipulación de datos.', technicalQuestions: ["Escribe una consulta SQL para encontrar el salario promedio por departamento, mostrando solo los departamentos con más de 10 empleados.", "Explica la diferencia entre `WHERE` y `HAVING` en SQL.", "Describe las funciones de ventana (window functions) en SQL y da un ejemplo de cómo usar `ROW_NUMBER()` o `RANK()`.", "¿Qué son las Common Table Expressions (CTEs) y cuándo son útiles?"] },
        { id: 'estadistica', name: 'Estadística Descriptiva e Inferencial', description: 'Bases matemáticas del análisis.', technicalQuestions: ["Diferencia entre media, mediana y moda. ¿Cuándo usarías cada una y cómo se ven afectadas por outliers?", "Explica qué es un p-valor en el contexto de una prueba de hipótesis. ¿Qué significa un p-valor pequeño?", "¿Qué es un intervalo de confianza y cómo se interpreta?", "Describe la diferencia entre correlación y causalidad."] },
      ]},
      { id: 'procesamiento_datos', title: 'Procesamiento y Limpieza', items: [
        { id: 'data_wrangling', name: 'Data Wrangling y Limpieza', description: 'Transformación de datos crudos.', technicalQuestions: ["Menciona tres técnicas comunes de limpieza de datos (ej: manejo de duplicados, corrección de errores tipográficos, estandarización de formatos).", "¿Cómo identificarías y tratarías outliers en un conjunto de datos? Menciona un método estadístico y uno visual.", "Explica el concepto de 'tidy data' (datos ordenados).", "¿Qué es la imputación de datos y cuándo se utiliza?"] },
        { id: 'etl', name: 'Procesos ETL', description: 'Extracción, Transformación y Carga de datos.', technicalQuestions: ["¿Qué significa ETL y cuáles son sus etapas principales? Describe brevemente cada una.", "Describe un desafío común en cada etapa del proceso ETL (Extracción, Transformación, Carga).", "¿Qué herramientas se pueden utilizar para implementar pipelines ETL (ej: Apache Airflow, AWS Glue, Azure Data Factory)?", "Explica la diferencia entre ETL y ELT."] },
        { id: 'apis_datos', name: 'Uso de APIs para obtención de datos', description: 'Conexión a fuentes de datos externas.', technicalQuestions: ["¿Cómo obtendrías datos de una API REST utilizando Python y la librería `requests`?", "Menciona consideraciones importantes al trabajar con APIs (rate limiting, autenticación, paginación).", "¿Qué es JSON y por qué es comúnmente usado en APIs? ¿Conoces otros formatos?", "Describe cómo manejarías errores al consumir una API (ej: códigos de estado HTTP)."] },
      ]},
      { id: 'visualizacion_datos', title: 'Visualización de Datos', items: [
        { id: 'matplotlib_seaborn', name: 'Matplotlib y Seaborn (Python)', description: 'Creación de gráficos estáticos e interactivos.', technicalQuestions: ["¿Cuándo usarías un histograma vs un gráfico de barras? ¿Qué tipo de datos representa cada uno?", "Describe cómo crear un scatter plot con Matplotlib y para qué tipo de análisis es útil.", "¿Qué ventajas ofrece Seaborn sobre Matplotlib para ciertos tipos de gráficos estadísticos?", "Menciona 3 tipos de gráficos que puedes crear con Seaborn y su propósito."] },
        { id: 'plotly_dash', name: 'Plotly y Dash (Python)', description: 'Dashboards interactivos.', technicalQuestions: ["¿Qué tipo de interactividad puedes agregar a los gráficos con Plotly (hover, zoom, selección)?", "Explica la arquitectura básica de una aplicación Dash (layout y callbacks). ¿Cómo funcionan los callbacks?", "¿Para qué tipo de proyectos es adecuado Dash en comparación con herramientas de BI como Tableau?", "Menciona un componente de entrada y un componente de salida comunes en Dash."] },
        { id: 'tableau_powerbi', name: 'Herramientas BI (Tableau, Power BI)', description: 'Plataformas de visualización y BI.', technicalQuestions: ["Menciona tres características clave de herramientas como Tableau o Power BI que las hacen poderosas para el análisis de datos.", "¿Qué es un dashboard y cuáles son las buenas prácticas para su diseño efectivo?", "Describe cómo conectarías una fuente de datos (ej: un archivo Excel o una base de datos SQL) en Tableau o Power BI.", "Explica el concepto de 'medidas' y 'dimensiones' en estas herramientas."] },
      ]},
      { id: 'ml_basico', title: 'Machine Learning (Básico)', items:
        [
          { id: 'conceptos_ml', name: 'Conceptos de Machine Learning', description: 'Aprendizaje supervisado y no supervisado.', technicalQuestions: ["Diferencia entre aprendizaje supervisado y no supervisado. Da un ejemplo de un algoritmo para cada tipo.", "Explica el concepto de 'overfitting' y 'underfitting'. ¿Cómo se pueden prevenir?", "¿Qué es la ingeniería de características (feature engineering) y por qué es importante?", "Describe el proceso de división de datos en conjuntos de entrenamiento, validación y prueba."] },
          { id: 'scikit_learn', name: 'Scikit-learn (Python)', description: 'Librería para modelos de ML.', technicalQuestions: ["Describe el flujo de trabajo típico para entrenar un modelo con Scikit-learn (instanciar el modelo, `fit`, `predict`).", "¿Qué es un 'Pipeline' en Scikit-learn y para qué sirve? Da un ejemplo.", "Nombra dos algoritmos de clasificación (ej: Logistic Regression, SVM) y dos de regresión (ej: Linear Regression, Decision Tree Regressor) disponibles en Scikit-learn.", "¿Cómo se realiza el preprocesamiento de datos (escalado, codificación de variables categóricas) con Scikit-learn?"] },
          { id: 'evaluacion_modelos', name: 'Evaluación de Modelos', description: 'Métricas y técnicas.', technicalQuestions: ["Explica las métricas de Accuracy, Precision, Recall y F1-score para problemas de clasificación. ¿Cuándo es preferible usar una sobre otra?", "¿Qué es la validación cruzada (cross-validation) y por qué es importante? Describe k-fold cross-validation.", "Describe la curva ROC (Receiver Operating Characteristic) y el AUC (Area Under the Curve). ¿Qué indican?", "Para problemas de regresión, ¿qué métricas comunes se utilizan para evaluar un modelo (ej: MAE, MSE, R-squared)?"] },
        ]
      },
    ],
  },
];

export const RESOURCES_DATA: Resource[] = [
  { id: 'res1', title: 'MDN Web Docs (HTML, CSS, JS)', type: 'Documentación', description: 'Referencia completa para tecnologías web.', url: 'https://developer.mozilla.org/', tags: ['frontend', 'html', 'css', 'javascript', 'dom'] },
  { id: 'res2', title: 'FreeCodeCamp', type: 'Curso Online', description: 'Aprende a programar gratis. Construye proyectos.', url: 'https://www.freecodecamp.org/', tags: ['frontend', 'backend', 'data analysis', 'fullstack', 'html', 'css', 'javascript', 'react', 'nodejs', 'python_datos', 'sql_datos', 'git'] },
  { id: 'res3', title: 'React Official Docs', type: 'Documentación', description: 'Documentación oficial de React.', url: 'https://react.dev/', tags: ['frontend', 'react', 'javascript', 'state_management'] },
  { id: 'res4', title: 'Node.js Official Docs', type: 'Documentación', description: 'Documentación oficial de Node.js.', url: 'https://nodejs.org/en/docs', tags: ['backend', 'nodejs', 'javascript'] },
  { id: 'res5', title: 'Stack Overflow', type: 'Comunidad', description: 'Comunidad de Q&A para programadores.', url: 'https://stackoverflow.com/', tags: ['general', 'programming', 'html', 'css', 'javascript', 'react', 'nodejs', 'python_datos', 'sql', 'git', 'docker'] },
  { id: 'res6', title: 'Django Project Docs', type: 'Documentación', description: 'Documentación oficial de Django.', url: 'https://docs.djangoproject.com/', tags: ['backend', 'python_backend', 'python'] },
  { id: 'res7', title: 'Kaggle', type: 'Comunidad', description: 'Plataforma para científicos de datos y competencias de ML.', url: 'https://www.kaggle.com/', tags: ['data analysis', 'machine learning', 'python_datos', 'r_lang', 'scikit_learn', 'evaluacion_modelos'] },
  { id: 'res8', title: 'Coursera: Data Science Specializations', type: 'Curso Online', description: 'Cursos y especializaciones en ciencia de datos.', url: 'https://www.coursera.org/browse/data-science', tags: ['data analysis', 'python_datos', 'r_lang', 'machine learning', 'sql_datos', 'estadistica', 'data_wrangling', 'matplotlib_seaborn', 'conceptos_ml'] },
  { id: 'res9', title: 'CSS-Tricks', type: 'Artículo', description: 'Artículos y tutoriales sobre CSS.', url: 'https://css-tricks.com/', tags: ['frontend', 'css', 'responsive'] },
  { id: 'res10', title: 'Dev.to', type: 'Comunidad', description: 'Comunidad de desarrolladores de software.', url: 'https://dev.to/', tags: ['general', 'programming', 'frontend', 'backend', 'data analysis', 'vue', 'angular'] },
  { id: 'res11', title: 'The Odin Project', type: 'Curso Online', description: 'Currículum completo para desarrollo web full-stack.', url: 'https://www.theodinproject.com/', tags: ['frontend', 'backend', 'fullstack', 'html', 'css', 'javascript', 'nodejs', 'sql', 'git', 'apis_frontend', 'rest_api'] },
  { id: 'res12', title: 'DataCamp', type: 'Curso Online', description: 'Cursos interactivos de ciencia de datos y programación.', url: 'https://www.datacamp.com/', tags: ['data analysis', 'python_datos', 'r_lang', 'sql_datos', 'estadistica', 'matplotlib_seaborn', 'scikit_learn'] },
  { id: 'res13', title: 'Vue.js Official Docs', type: 'Documentación', description: 'Documentación oficial de Vue.js.', url: 'https://vuejs.org/', tags: ['frontend', 'vue', 'javascript', 'state_management'] },
  { id: 'res14', title: 'Spring Framework Docs', type: 'Documentación', description: 'Documentación oficial de Spring Framework (Java).', url: 'https://spring.io/docs', tags: ['backend', 'java_backend', 'java'] },
  { id: 'res15', title: 'Awesome Python', type: 'Herramienta', description: 'Lista curada de frameworks, librerías y software Python.', url: 'https://github.com/vinta/awesome-python', tags: ['python_backend', 'data analysis', 'python', 'python_datos', 'django', 'flask'] },
  { id: 'res16', title: 'Eloquent JavaScript', type: 'Curso Online', description: 'Un libro moderno sobre JavaScript.', url: 'https://eloquentjavascript.net/', tags: ['javascript', 'frontend', 'nodejs', 'dom'] },
  { id: 'res17', title: 'W3Schools HTML Tutorial', type: 'Documentación', description: 'Tutoriales y referencias de HTML.', url: 'https://www.w3schools.com/html/', tags: ['html', 'frontend'] },
  { id: 'res18', title: 'Git Handbook', type: 'Documentación', description: 'Guía de GitHub para aprender Git.', url: 'https://guides.github.com/introduction/git-handbook/', tags: ['git', 'herramientas_frontend', 'devops_backend'] },
  { id: 'res19', title: 'Roadmap.sh', type: 'Herramienta', description: 'Roadmaps comunitarios para desarrolladores.', url: 'https://roadmap.sh/', tags: ['general', 'frontend', 'backend', 'devops_backend', 'angular', 'vue', 'react'] },
  { id: 'res20', title: 'Angular Official Docs', type: 'Documentación', description: 'Documentación oficial de Angular.', url: 'https://angular.io/docs', tags: ['frontend', 'angular', 'javascript', 'typescript', 'state_management'] },
  { id: 'res21', title: 'Redux Official Docs', type: 'Documentación', description: 'Documentación oficial de Redux.', url: 'https://redux.js.org/', tags: ['frontend', 'react', 'state_management', 'redux'] },
  { id: 'res22', title: 'Webpack Official Docs', type: 'Documentación', description: 'Documentación oficial de Webpack.', url: 'https://webpack.js.org/concepts/', tags: ['frontend', 'bundlers', 'webpack'] },
  { id: 'res23', title: 'Vite Official Docs', type: 'Documentación', description: 'Documentación oficial de Vite.', url: 'https://vitejs.dev/', tags: ['frontend', 'bundlers', 'vite'] },
  { id: 'res24', title: 'Jest Official Docs', type: 'Documentación', description: 'Documentación oficial de Jest.', url: 'https://jestjs.io/docs/getting-started', tags: ['frontend', 'testing_frontend', 'jest', 'javascript'] },
  { id: 'res25', title: 'PostgreSQL Official Docs', type: 'Documentación', description: 'Documentación oficial de PostgreSQL.', url: 'https://www.postgresql.org/docs/', tags: ['backend', 'sql', 'bases_de_datos_backend'] },
  { id: 'res26', title: 'MongoDB Official Docs', type: 'Documentación', description: 'Documentación oficial de MongoDB.', url: 'https://www.mongodb.com/docs/', tags: ['backend', 'nosql', 'bases_de_datos_backend', 'mongodb'] },
  { id: 'res27', title: 'JWT.io', type: 'Herramienta', description: 'Información y herramientas para JSON Web Tokens.', url: 'https://jwt.io/', tags: ['backend', 'autenticacion_autorizacion', 'jwt', 'apis_backend'] },
  { id: 'res28', title: 'Docker Official Docs', type: 'Documentación', description: 'Documentación oficial de Docker.', url: 'https://docs.docker.com/', tags: ['backend', 'devops_backend', 'docker'] },
  { id: 'res29', title: 'Kubernetes Official Docs', type: 'Documentación', description: 'Documentación oficial de Kubernetes.', url: 'https://kubernetes.io/docs/', tags: ['backend', 'devops_backend', 'kubernetes'] },
  { id: 'res30', title: 'AWS Documentation', type: 'Documentación', description: 'Documentación oficial de Amazon Web Services.', url: 'https://aws.amazon.com/documentation/', tags: ['backend', 'cloud_platforms', 'aws', 'devops_backend'] },
  { id: 'res31', title: 'Pandas Official Docs', type: 'Documentación', description: 'Documentación oficial de Pandas.', url: 'https://pandas.pydata.org/docs/', tags: ['data analysis', 'python_datos', 'pandas', 'data_wrangling'] },
  { id: 'res32', title: 'NumPy Official Docs', type: 'Documentación', description: 'Documentación oficial de NumPy.', url: 'https://numpy.org/doc/', tags: ['data analysis', 'python_datos', 'numpy'] },
  { id: 'res33', title: 'RDocumentation.org', type: 'Documentación', description: 'Documentación para paquetes de R.', url: 'https://www.rdocumentation.org/', tags: ['data analysis', 'r_lang'] },
  { id: 'res34', title: 'Tableau Public Resources', type: 'Curso Online', description: 'Recursos y tutoriales para Tableau.', url: 'https://public.tableau.com/app/resources/learn', tags: ['data analysis', 'tableau_powerbi', 'visualizacion_datos'] },
  { id: 'res35', title: 'Scikit-learn Official Docs', type: 'Documentación', description: 'Documentación oficial de Scikit-learn.', url: 'https://scikit-learn.org/stable/documentation.html', tags: ['data analysis', 'scikit_learn', 'machine learning', 'conceptos_ml', 'evaluacion_modelos'] },
];
